config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :purchases

      resources :comments

      resources :categories

      resources :items

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "items#index"
  resources :purchases
  resources :comments
  resources :categories
  resources :items
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
require "open-uri"
class Item < ApplicationRecord
  before_validation :geocode_location_url

  def geocode_location_url
    if location_url.present?
      url = "https://maps.googleapis.com/maps/api/geocode/json?key=#{ENV['GMAP_API_KEY']}&address=#{URI.encode(location_url)}"

      raw_data = open(url).read

      parsed_data = JSON.parse(raw_data)

      if parsed_data["results"].present?
        self.location_url_latitude = parsed_data["results"][0]["geometry"]["location"]["lat"]

        self.location_url_longitude = parsed_data["results"][0]["geometry"]["location"]["lng"]

        self.location_url_formatted_address = parsed_data["results"][0]["formatted_address"]
      end
    end
  end
  mount_base64_uploader :image, ImageUploader

  # Direct associations

  belongs_to :category

  has_many   :purchases,
             dependent: :destroy

  has_many   :comments,
             dependent: :destroy

  belongs_to :user

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    title
  end
end

app/controllers/api/v1/items_controller.rb
class Api::V1::ItemsController < Api::V1::GraphitiController
  def index
    items = ItemResource.all(params)
    respond_with(items)
  end

  def show
    item = ItemResource.find(params)
    respond_with(item)
  end

  def create
    item = ItemResource.build(params)

    if item.save
      render jsonapi: item, status: :created
    else
      render jsonapi_errors: item
    end
  end

  def update
    item = ItemResource.find(params)

    if item.update_attributes
      render jsonapi: item
    else
      render jsonapi_errors: item
    end
  end

  def destroy
    item = ItemResource.find(params)

    if item.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: item
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :current_user_must_be_item_user,
                only: %i[edit update destroy]

  before_action :set_item, only: %i[show edit update destroy]

  def index
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true).includes(:user, :comments,
                                                :purchases, :category).page(params[:page]).per(10)
    @location_hash = Gmaps4rails.build_markers(@items.where.not(location_url_latitude: nil)) do |item, marker|
      marker.lat item.location_url_latitude
      marker.lng item.location_url_longitude
    end
  end

  def show
    @purchase = Purchase.new
    @comment = Comment.new
  end

  def new
    @item = Item.new
  end

  def edit; end

  def create
    @item = Item.new(item_params)

    if @item.save
      message = "Item was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @item, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to @item, notice: "Item was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    message = "Item was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to items_url, notice: message
    end
  end

  private

  def current_user_must_be_item_user
    set_item
    unless current_user == @item.user
      redirect_back fallback_location: root_path,
                    alert: "You are not authorized for that."
    end
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:title, :image, :price, :category_id,
                                 :description, :user_id, :location_url)
  end
end

app/views/items/_all_photos_map.html.erb
<div id="location_map" style="height: 480px;"></div>
<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'location_map'}}, function(){
    markers = handler.addMarkers(<%= raw @location_hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/items/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Item #<%= item.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Title</dt>
      <dd><%= item.title %></dd>

      <dt>Image</dt>
      <dd>
        <%= cl_image_tag @item.image, class: "img-fluid" %>
      </dd>

      <dt>Price</dt>
      <dd><%= item.price %></dd>

      <dt>Category</dt>
      <dd>
        <% if @item.category.present? %>
          <%= link_to item.category, item.category %>
        <% end %>
      </dd>

      <dt>Description</dt>
      <dd><%= item.description %></dd>

      <dt>User</dt>
      <dd>
        <% if @item.user.present? %>
          <%= link_to item.user, item.user %>
        <% end %>
      </dd>

      <dt>Location url</dt>
      <dd>
        <div>
          <%= render partial: "items/one_photo_map" %>
        </div>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back item, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <% if current_user == @item.user %>
          <%= link_to edit_item_url(item), class: "btn btn-block btn-sm btn-outline-secondary" do %>
            <i class="fas fa-edit"></i>
          <% end %>
        <% end %>
      </div>

      <div class="col">
        <% if current_user == @item.user %>
          <%= link_to item, method: :delete, data: { confirm: "Do you really want to delete this item?" }, class: "btn btn-block btn-outline-secondary" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(item.updated_at) %> ago
  </div>
</div>

app/views/items/_form.html.erb
<% was_validated = item.errors.any? %>

<%= form_with(model: item, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% title_class = "form-control" %>
    <% title_was_invalid = item.errors.include?(:title) %>

    <% if was_validated %>
      <% if title_was_invalid %>
        <% title_class << " is-invalid" %>
      <% else %>
        <% title_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :title %>
    <%= f.text_field :title, class: title_class, placeholder: "Enter title" %>
    <% if title_was_invalid %>
      <% item.errors.full_messages_for(:title).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% image_class = "form-control" %>
    <% image_was_invalid = item.errors.include?(:image) %>

    <% if was_validated %>
      <% if image_was_invalid %>
        <% image_class << " is-invalid" %>
      <% else %>
        <% image_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
    <% if image_was_invalid %>
      <% item.errors.full_messages_for(:image).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% price_class = "form-control" %>
    <% price_was_invalid = item.errors.include?(:price) %>

    <% if was_validated %>
      <% if price_was_invalid %>
        <% price_class << " is-invalid" %>
      <% else %>
        <% price_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :price %>
    <%= f.text_field :price, class: price_class, placeholder: "Enter price" %>
    <% if price_was_invalid %>
      <% item.errors.full_messages_for(:price).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% category_class = "form-control" %>
    <% category_was_invalid = item.errors.include?(:category) %>

    <% if was_validated %>
      <% if category_was_invalid %>
        <% category_class << " is-invalid" %>
      <% else %>
        <% category_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.all, :id, :to_s, {}, class: "form-control" %>
    <% if category_was_invalid %>
      <% item.errors.full_messages_for(:category).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% description_class = "form-control" %>
    <% description_was_invalid = item.errors.include?(:description) %>

    <% if was_validated %>
      <% if description_was_invalid %>
        <% description_class << " is-invalid" %>
      <% else %>
        <% description_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :description %>
    <%= f.text_area :description, class: description_class, placeholder: "Enter description" %>
    <% if description_was_invalid %>
      <% item.errors.full_messages_for(:description).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="form-group">
    <% location_url_class = "form-control" %>
    <% location_url_was_invalid = item.errors.include?(:location_url) %>

    <% if was_validated %>
      <% if location_url_was_invalid %>
        <% location_url_class << " is-invalid" %>
      <% else %>
        <% location_url_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :location_url %>
    <%= f.text_field :location_url, class: location_url_class, placeholder: "Enter location url" %>
    <% if location_url_was_invalid %>
      <% item.errors.full_messages_for(:location_url).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/items/_item_comments.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Comments

    <a data-toggle="collapse" href="#item_comments_new_form">
      Add comment
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @item.comments.each do |comment| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to comment, comment %>

        <%= link_to comment, method: :delete, data: { confirm: "Do you really want to delete this comment" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="item_comments_new_form">
        <%= render partial: "items/item_comments_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/items/_item_comments_new_form.html.erb
<%= form_with(model: @comment, local: true) do |f| %>

  <%= f.hidden_field :item_id, value: @item.id %>

  <div class="form-group">
    <%= f.label :user_id %>

    <%= f.collection_select :user_id, User.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :comment %>
    <%= f.text_area :comment, rows: "3", class: "form-control" %>
  </div>

  <%= f.submit "Create comment", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/items/_item_purchases.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Purchases

    <a data-toggle="collapse" href="#item_purchases_new_form">
      Add purchase
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @item.purchases.each do |purchase| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to purchase, purchase %>

        <%= link_to purchase, method: :delete, data: { confirm: "Do you really want to delete this purchase" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="item_purchases_new_form">
        <%= render partial: "items/item_purchases_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/items/_item_purchases_new_form.html.erb
<%= form_with(model: @purchase, local: true) do |f| %>

  <%= f.hidden_field :item_id, value: @item.id %>

  <div class="form-group">
    <%= f.label :user_id %>

    <%= f.collection_select :user_id, User.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.submit "Create purchase", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/items/_items_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "items_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :title_cont, "Title contains" %>
    <%= f.text_field :title_cont, :class => "form-control", :placeholder => "Title contains" %>
  </div>

  <div class="form-group">
    <%= f.label :description_cont, "Description contains" %>
    <%= f.text_field :description_cont, :class => "form-control", :placeholder => "Description contains" %>
  </div>

  <div class="form-group">
    <%= f.label :price, "Price" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :price_gteq, :class => "form-control", :placeholder => "Price greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :price_lteq, :class => "form-control", :placeholder => "Price less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :user_email_cont, "User email contains" %>
    <%= f.text_field :user_email_cont, :class => "form-control", :placeholder => "User email contains" %>
  </div>

  <div class="form-group">
    <%= f.label :category_name_cont, "Category name contains" %>
    <%= f.text_field :category_name_cont, :class => "form-control", :placeholder => "Category name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/items" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#items_filters">
  Show filters
</a>

app/views/items/_list_item.html.erb
<%= link_to item, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= item %>
    <small class="text-muted">
      <%= time_ago_in_words(item.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/items/_one_photo_map.html.erb
<div id="location_map" style="height: 480px;"></div>

<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'location_map'}}, function(){
    markers = handler.addMarkers([
      {
        "lat": <%= @item.location_url_latitude %>,
        "lng": <%= @item.location_url_longitude %>,
        "infowindow": "<h5><%= @item.created_at %></h5><small><%= @item.location_url_formatted_address %></small>"
      }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/items/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Item #<%= @item.id %>
      </h2>

      <div class="card-body">
        <%= render "form", item: @item %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Items

      <%= link_to new_item_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "items/items_search_form" %>
  </div>
</div>

<div class="row mb-3">
  <div class="col-md-12">
    <%= render partial: "items/all_photos_map" %>
  </div>
</div>


<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Items

        <%= link_to new_item_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @items, partial: "list_item", as: :item %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @items, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Item
      </h2>

      <div class="card-body">
        <%= render "form", item: @item %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @item, partial: "card", as: :item %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "items/item_comments" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "items/item_purchases" %>
  </div>
</div>